### ISSUE TITLE
Great project! how's the Whisper API coming along?

### ISSUE THREAD

**Issue by JimmyLv** [SpellcraftAI/openai-streams#19]

**Comment by robinsingh1** [comment]
++

**Comment by sebnun** [comment]
Thanks for this library, +1 for whisper :)

**Comment by ctjlewis** [comment]
OpenAI's Whisper API still does not support streaming. See https://github.com/openai/whisper/discussions/2.

Related:

- https://github.com/ggerganov/whisper.cpp
- https://github.com/chengsokdara/use-whisper
