### ISSUE TITLE
Some tokens are being dropped

### ISSUE THREAD

**Issue by GLips** [SpellcraftAI/openai-streams#36]
I'm having an issue where it seems some tokens are being dropped. Most frequently, it's the first token but in the attached screenshot below it looks like it might have dropped one in the middle too—the missing space between "I" and "assist".

<img width="388" alt="CleanShot 2023-05-22 at 10 07 42@2x" src="https://github.com/SpellcraftAI/openai-streams/assets/842883/a6370ae1-cfdb-4fd5-84de-4587bc5ccdce">

In order to confirm it wasn't a client-side only issue with my code, I logged each token as it was decoded via the new `onParse` callback. Even there the token was dropped.

In my initial search, I found [this thread on the OpenAI forums](https://community.openai.com/t/stream-response-from-v1-chat-completions-endpoint-is-missing-the-first-token/187835) describing a similar issue. If we're running into the same issue here, this may not be a problem with `openai-streams` at all, but instead with `eventsource-parser`.

I'll post more findings—and hopefully a fix too—once I look into it. I plan on investigating in the next couple days, but if anyone has an idea of what the issue is I'd love to hear any thoughts.

**Comment by ctjlewis** [comment]
Can we repro this in any way? If we can, I can test for it and we can fix it.

I originally wrote the SSE parser myself, but `eventsource-parser` seemed stabler.

**Comment by ctjlewis** [comment]
Can you put together a repository that reproduces this?

**Comment by GLips** [comment]
Took another look today and it must have been strangeness on OpenAI's end. Closing this issue for now. Will re-open if I can reproduce it reliably and confirm it's coming from this library. Thanks!
