### ISSUE TITLE
A question about onDone callback

### ISSUE THREAD

**Issue by daimajia** [SpellcraftAI/openai-streams#40]
Thanks for your working on this awesome lib.

 I'm not that familiar with the streaming api, just tested a few cases, in the case, the `onDone` function randomely stopped.
. I guess `controller.close()` will terminate the whole process, even if the `onDone` is running?  

https://github.com/SpellcraftAI/openai-streams/blob/07182c7313/src/lib/streaming/streams.ts#L57

So, should we invoke the `onDone` before the `controller.close();` ？

**Comment by ctjlewis** [comment]
`onDone()` only fires once, when the stream has finished. `controller.close()` will not interrupt it, it's just an event listener basically.

**Comment by mixasite** [comment]
@daimajia you are right. This is not visible during local testing, but it will not work on Vercel. As soon as the response is returned, Vercel will kill the process. So, if you are doing async work in `onDone` method, they won't get executed

**Comment by mixasite** [comment]
if you are using Vercel, I suggest trying their AI library. `onFinal` works as expected:
https://sdk.vercel.ai/docs/api-reference/openai-stream

```
export async function POST(req: Request) {
  const { messages } = await req.json();
  // Create a chat completion using OpenAI
  const response = await openai.chat.completions.create({
    model: 'gpt-4',
    stream: true,
    messages,
  });
 
  // Transform the response into a readable stream
  const stream = OpenAIStream(response, {
      onFinal: async (content) => {
        // run your async logic here
      }
  });
 
  // Return a StreamingTextResponse, which can be consumed by the client
  return new StreamingTextResponse(stream);
}
```

**Comment by daimajia** [comment]
thx @mixasite !
