### ISSUE TITLE
Is it possible cancel a stream

### ISSUE THREAD

**Issue by Akifcan** [SpellcraftAI/openai-streams#43]
Hello I created stream with openai-streams package but streams still up even I close the page. so can stop the streaming before I close a webpage

**Comment by ctjlewis** [comment]
Yes, you can pass an `AbortController()` into the fetch params and cancel with `controller.abort()`.

**Comment by Akifcan** [comment]
Hello I tried abortController fetch is cancelling but I still see the logs

**Comment by ctjlewis** [comment]
Please provide a reproduction and I'll reopen.
