### ISSUE TITLE
Hi, you can use `publint` to check publish package errors

### ISSUE THREAD

**Issue by u3u** [SpellcraftAI/openai-streams#45]
Check package errors: https://publint.dev/openai-streams

<img width="1224" alt="image" src="https://github.com/SpellcraftAI/openai-streams/assets/20062482/02d5745c-7d23-47fc-a622-f5f0df416f15">

Because I just received a large number of release notifications, it seems that they are all for compatibility with `cjs`.
You can use [`tsup`](https://github.com/egoist/tsup) or [`unbuild`](https://github.com/unjs/unbuild) to be compatible with both `cjs` and `esm`.

You can refer to the following articles for more details:
https://antfu.me/posts/publish-esm-and-cjs
https://antfu.me/posts/types-for-sub-modules

**Comment by ctjlewis** [comment]
When will an unused conditional export ever cause an error, exactly?

TS Module spec intentionally do not support CJS by default, it was manually added here because I specifically needed CJS. The versions are manually pinned and it's a second-class citizen.

**Comment by ctjlewis** [comment]
Publint seems kind of cool though. The unused conditional exports are not errors, but it's fine to warn for them.

**Comment by u3u** [comment]
> When will an unused conditional export ever cause an error, exactly?

I don't quite understand this, I haven't encountered this problem before.

Actually, before this, I used it like this in CJS (see [Pure ESM package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)):

```ts
const { OpenAI } = await import('openai-streams/node')

const stream = await OpenAI(
  'chat',
  {
    messages: [],
    model: 'gpt-3.5-turbo',
  },
  { controller: abortController }
)
```
