### ISSUE TITLE
Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by bewallyt** [SpellcraftAI/openai-streams#50]
Running into this issue when invoking an instance of OpenAIEdgeClient in the latest versions 5.20, etc. This is on Vercel's edge functions.

node:fs
Module build failed: UnhandledSchemeError: Reading from "node:fs" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:fs
./node_modules/fetch-blob/from.js
./node_modules/node-fetch/src/index.js
./node_modules/openai-streams/dist/lib/backoff.js
./node_modules/openai-streams/dist/lib/openai/edge.js
./node_modules/openai-streams/dist/lib/openai/index.js
./node_modules/openai-streams/dist/lib/index.js
./node_modules/openai-streams/dist/index.js

Reverting to 5.15 fixed it.

**Comment by ctjlewis** [comment]
Hey, thanks for catching that. This is fixed in v5.21.0.

**Comment by ctjlewis** [comment]
Actually that fix didn't work - but it will be in soon.

**Comment by ctjlewis** [comment]
OK, this is actually fixed in `>6.x`, for real this time. Super sorry about that!

**Comment by bewallyt** [comment]
@ctjlewis awesome - thanks for the quick turnaround! 🙇
